version: '3'
services:
  myapp:
    # image: my-image # localde my-image isminde bir image önceden oluşturmuşsanız, ports kısmına kadar olanları yoruma çekin.
    # aşağıdaki kısım için önceden imaj oluşturmanıza gerek yok. Burada oluşturuyor. Yukarıdaki image kısmını yoruma çekin.
    container_name: myapp
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
