- name: create docker
  hosts: _development
  become: true
  tasks:
    - name: install docker form galaxy
      include_role:
        name: geerlingguy.docker

    - name: install pip # docker_image çalıştırma için sdk gerekliymiş. onun içinde pip gerekli.
      package:
        name: python3-pip
        state: present
    - name: install docker sdk
      pip: 
        name: docker
        
- name: create postgresql database
  hosts: _ansible_postgresql
  become: true
  roles:
    - postgre
- name: create nodejs server
  hosts: _ansible_nodejs
  become: true
  roles:
    - nodejs
- name: create react server
  hosts: _ansible_react
  become: true
  roles:
    - react
