apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: db-pv-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: mysql-configmap
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: mysecret   
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: db-pv-storage
            mountPath: /var/lib/mysql