version: "3.7"

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hoop123
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1

  mybookstore:
    image: ilgea/bookstore:latest
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"